### ISSUE TITLE
Doesn't build with boost v1.85.0+

### ISSUE THREAD

**Issue by eilvelia** [cgao3/benzene-vanilla-cmake#18]
```
       > /build/source/src/util/Misc.cpp: In function 'void benzene::MiscUtil::FindProgramDir(int, char**)':
       > /build/source/src/util/Misc.cpp:38:36: error: 'class boost::filesystem::path' has no member named 'branch_path'
       >    38 |         programDir = path(argv[0]).branch_path();
       >       |                                    ^~~~~~~~~~~
       > /build/source/src/util/Misc.cpp: In function 'std::string benzene::MiscUtil::OpenFile(std::string, std::ifstream&)':
       > /build/source/src/util/Misc.cpp:85:11: error: 'class boost::filesystem::path' has no member named 'normalize'
       >    85 |         p.normalize();
       >       |           ^~~~~~~~~
       > /build/source/src/util/Misc.cpp:97:11: error: 'class boost::filesystem::path' has no member named 'normalize'
       >    97 |         p.normalize();
       >       |           ^~~~~~~~~
       > /build/source/src/util/Misc.cpp:109:11: error: 'class boost::filesystem::path' has no member named 'normalize'
       >   109 |         p.normalize();
       >       |           ^~~~~~~~~
       > make[2]: *** [src/util/CMakeFiles/util.dir/build.make:132: src/util/CMakeFiles/util.dir/Misc.cpp.o] Error 1
```

https://www.boost.org/users/history/version_1_85_0.html
> - Removed APIs that were previously declared deprecated. In particular, path and recursive_directory_iterator member functions, is_regular, copy_directory, symbolic_link_exists, complete, copy_option, symlink_option, as well as boost/filesystem/convenience.hpp and boost/filesystem/path_traits.hpp headers were removed. Possible replacements for the removed components are mentioned in the documentation.

`.branch_path()` should be replaced with `.parent_path()`, and `.normalize()` should be replaced with `.lexically_normal()`.
